### ISSUE TITLE
Motivation for scijs cleanup

### ISSUE THREAD

**Issue by rreusser** [welch/gencov#1]
Was caught off guard by the fact that one of my packages had a dependent! :smile: Glad to see it getting use, but it's been a rocky road learning to write rigorously correct/useful/straightforward numerical library code. Some of what you've used is ripe for refactoring/cleanup/blowing away.

Long story short, if you have feedback or demands, don't hesitate to ask! (SVD is… in progress…) [scijs/contributing](https://github.com/scijs/contributing/issues) is a decent place. Should close some issue over there, but feedback is appreciated and will get noticed.

**Comment by welch** [comment]
I'm a fan of your work! And yes, numerical libraries and just-right APIs are hard (and in javascript! yeesh).

I'm a fan of the BLAS modules that have appeared. Not because I like obscure fortran names, but because I hope to swap in the real fortran libraries under the hood someday (server side). I wonder if ndarray will get itself a full scipy-ish API or if we'll be calling these things directly for the foreseeable future.

Mostly I wish things weren't sliced so thinly for importing -- it is a constant debate whether to import yet another thing or replicate the small thing needed, in order to lose a dependency. But there's no clear answer for useful independent subsets. It is really difficult with do-all numeric libraries not to end up importing the entire universe just to do a dot product, so you end up writing it yourself over and over. 

I've not quite made peace with the npm best practice of slice thinly and import lots of things, but when I think of page loads and shrinkwrap it is more compelling.

**Comment by rreusser** [comment]
Yeah, ultimately I think the thinly sliced modules are better in just about every way except for actually using them (development, discovery, etc.). There was a repo whose goal was to assemble scijs into a numpy-like namespace, but I'm unable to find it (and reached out and got no response).

Possible approaches:
- A master build script that pulls everything into a single namespace. I think this'd be too cumbersome.
- scijs-*-packages modules (e.g. scijs-ndarray-packages) that would import all the ndarray-compatible functions into a namespace. scijs-signal-packages for dsp-type stuff. Etc.
- Use the slash trick to roll things up a bit (see, for example: [scijs/window-functions](https://github.com/scijs/window-functions#usage)). This seems dangerous because I don't think it's possible to roll things up enough to be useful without going back to gigantic packages.

Good feedback though. I think my next project will be to tidy up ndarray packages and maybe make a single import with things cleaned up a bit. Thanks!

**Comment by rreusser** [comment]
Oh, or it could just be a documentation issue too. The site is relatively new and needs another update, but see: http://scijs.net/packages/

**Comment by welch** [comment]
thanks, http://scijs.net/packages/ is just what I needed, I was not getting the high-level view by searching npm.

I'm curious about naming and calling conventions. linear algebra is off and running with ndarray-\* , but statistics is a little random (ahem). I'm inclined to break out my orthogonal generator and throw it and gencov at your statistics collection, with conforming naming if there were a brand-name pattern like ndarray-*. Also, should scijs packages assume ndarrays for matrices? vectors?

**Comment by rreusser** [comment]
First of all, you've hit the nail on the head. I don't know the perfect answer, but you're spot-on on the concerns. Long story short, _this_ is why I think numerical computation is difficult in js: because you can't overload operators and create a syntax that's both expressive, concise, and avoids tons of boilerplate.

Specific points:
- **naming conventions**: a lot of scijs was migrated over from @mikolalysenko's repos that were created (long before I showed up at the last minute :smile:) before there really was a scijs. Some things are a little inconsistent, but I've raised most of these same concerns and have had to content myself with the answer: the primary goal at the moment is to improve things as you go and create new things that are good, clearly documented, and useful. So if you're interested in contributing and anything isn't clear, don't hesitate to ask for suggestions/feedback!
- ndarray-\* sounds fine for non-linear-algebra modules if they're heavily matrix-based. In general, I think it's best to allow plain vectors where ndarrays aren't really necessary and ndarrays where matrices are needed, although I've been thinking of an ndarray-cast module that would cast vectors to ndarrays so that you can [be conservative in what you do and liberal in what you accept](https://en.wikipedia.org/wiki/Robustness_principle). ndarrays are little more than a wrapper with strides and offsets, so although it's definitely best to avoid creating and garbage-collecting them, they're not too heavy.

Honestly, I view scijs in its current form as a stepping stone toward something more numpy-grade. I imagine it's easier to create something like that by reorganizing existing (MIT-licensed) pieces than it is to create it from nothing at all, so I'm hoping that if I write and test an ODE integrator, it'll both be useful and maybe fit into something larger down the road by just expanding the types it accepts or something.

Also honestly, you should look at [compute.io](https://github.com/compute-io), [distributions.io](https://github.com/compute-io), and [https://github.com/dstructs](https://github.com/dstructs). They have an impressive statistics collection and are very rigorous about naming/calling conventions, 100% test coverage, etc. The result is a lot more type-checking and [enumeration of use-cases](https://github.com/compute-io/erf/tree/master/lib). I don't know whether that's the right or wrong answer, and I'm conflicted between building out scijs stuff and jumping on board the test coverage train…

**Comment by rreusser** [comment]
Also, regarding matrices vs. vectors vs. arrays vs. ndarrays, there's this: https://www.npmjs.com/package/ndarray-pack

**Comment by rreusser** [comment]
Haha, just found this again. Got another contributor so blas-level2 is getting some much-needed cleanup. Looking like a minor version bump and more functionality on its way…

**Comment by rreusser** [comment]
I'll close this out since the motivation has (at long last) done its job :+1:
